### ISSUE TITLE
Use Java 1.7 instead of Java 1.8 to allow use on Android

### ISSUE THREAD

**Issue by gaffo** [OneBusAway/onebusaway-client-library#13]
Could we downgrade this or have a fork for 1.7?

**Comment by barbeau** [comment]
@gaffo Have you tried changing and compiling with 1.7?  IIRC I started with 1.8 thinking I'd use some of the new time utilities there, but don't recall if I ever actually used them.

I don't philosophically have an objection to changing to Java 1.7 if that's a blocking factor.

Also, have you tried targeting N preview, which should support Java 8 - https://developer.android.com/preview/j8-jack.html?

**Comment by barbeau** [comment]
Build using Java 7 seems to pass fine on Travis - https://travis-ci.org/OneBusAway/onebusaway-client-library/builds/131143311.

**Comment by barbeau** [comment]
Whoops, that was actually still using Java 8.  I'll test again.

**Comment by barbeau** [comment]
Ok, [this branch](https://github.com/OneBusAway/onebusaway-client-library/tree/java7) still passes when actually compiling on Java 7:
https://travis-ci.org/OneBusAway/onebusaway-client-library/builds/131148408

**Comment by barbeau** [comment]
PR for this at https://github.com/OneBusAway/onebusaway-client-library/pull/14.

**Comment by barbeau** [comment]
@gaffo New 1.0.0-SNAPSHOT artifact built using Java 1.7 should be available via the OBA Maven repo shortly, as soon as Jenkins finishes the build and pushes it.  Please give it a try and let me know if it works!

**Comment by gaffo** [comment]
Awesome, thanks! I'd love 1.8 as well but sadly not there in java yet. Works.
